In [10]:
import pandas as pd

In [11]:
parquet_file=r'C:\Users\playe\Documents\Trabajos\TFG-RAG-VDB\data_test\train-00000-of-00001.parquet'

In [12]:
df = pd.read_parquet(parquet_file, engine='auto')
pd.read_parquet(parquet_file, engine='auto')

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
1,5733be284776f4190066117f,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is in front of the Notre Dame Main Building?,"{'text': ['a copper statue of Christ'], 'answe..."
2,5733be284776f41900661180,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",The Basilica of the Sacred heart at Notre Dame...,"{'text': ['the Main Building'], 'answer_start'..."
3,5733be284776f41900661181,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is the Grotto at Notre Dame?,{'text': ['a Marian place of prayer and reflec...
4,5733be284776f4190066117e,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What sits on top of the Main Building at Notre...,{'text': ['a golden statue of the Virgin Mary'...
...,...,...,...,...,...
87594,5735d259012e2f140011a09d,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",In what US state did Kathmandu first establish...,"{'text': ['Oregon'], 'answer_start': [229]}"
87595,5735d259012e2f140011a09e,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",What was Yangon previously known as?,"{'text': ['Rangoon'], 'answer_start': [414]}"
87596,5735d259012e2f140011a09f,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,"{'text': ['Minsk'], 'answer_start': [476]}"
87597,5735d259012e2f140011a0a0,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,"{'text': ['1975'], 'answer_start': [199]}"
87598,5735d259012e2f140011a0a1,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,"{'text': ['Kathmandu Metropolitan City'], 'ans..."

In [13]:
print(df['context'][1])

Architecturally, the school has a Catholic character. Atop the Main Building's gold dome is a golden statue of the Virgin Mary. Immediately in front of the Main Building and facing it, is a copper statue of Christ with arms upraised with the legend "Venite Ad Me Omnes". Next to the Main Building is the Basilica of the Sacred Heart. Immediately behind the basilica is the Grotto, a Marian place of prayer and reflection. It is a replica of the grotto at Lourdes, France where the Virgin Mary reputedly appeared to Saint Bernadette Soubirous in 1858. At the end of the main drive (and in a direct line that connects through 3 statues and the Gold Dome), is a simple, modern stone statue of Mary.

In [14]:
df.drop_duplicates(subset=['context'])

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
5,5733bf84d058e614000b61be,University_of_Notre_Dame,"As at most other universities, Notre Dame's st...",When did the Scholastic Magazine of Notre dame...,"{'text': ['September 1876'], 'answer_start': [..."
10,5733bed24776f41900661188,University_of_Notre_Dame,The university is the major seat of the Congre...,Where is the headquarters of the Congregation ...,"{'text': ['Rome'], 'answer_start': [119]}"
15,5733a6424776f41900660f51,University_of_Notre_Dame,The College of Engineering was established in ...,How many BS level degrees are offered in the C...,"{'text': ['eight'], 'answer_start': [487]}"
20,5733a70c4776f41900660f64,University_of_Notre_Dame,All of Notre Dame's undergraduate students are...,What entity provides help with the management ...,"{'text': ['Learning Resource Center'], 'answer..."
...,...,...,...,...,...
87574,5735d0026c16ec1900b92815,Kathmandu,"Institute of Medicine, the central college of ...",Of what university is the Institute of Medicin...,"{'text': ['Tribhuwan'], 'answer_start': [46]}"
87579,5735d07d012e2f140011a087,Kathmandu,Football and Cricket are the most popular spor...,"Along with cricket, what sport is highly popul...","{'text': ['Football'], 'answer_start': [0]}"
87584,5735d0f46c16ec1900b92823,Kathmandu,The total length of roads in Nepal is recorded...,"As of 2004, how many kilometers of road existe...","{'text': ['17,182'], 'answer_start': [54]}"
87589,5735d1a86c16ec1900b92831,Kathmandu,The main international airport serving Kathman...,What is Nepal's primary airport for internatio...,"{'text': ['Tribhuvan International Airport'], ..."
87594,5735d259012e2f140011a09d,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to...",In what US state did Kathmandu first establish...,"{'text': ['Oregon'], 'answer_start': [229]}"

In [17]:
df.drop_duplicates(subset=['title'])

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
269,56be85543aeaaa14008c9063,Beyoncé,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,"{'text': ['in the late 1990s'], 'answer_start'..."
1027,5733bd9bd058e614000b6199,Montana,Montana i/mɒnˈtænə/ is a state in the Western ...,Where does the state's name come from?,"{'text': ['Spanish word montaña (mountain)'], ..."
1177,5733bdc4d058e614000b61a3,Genocide,"The phrase ""in whole or in part"" has been subj...","In the judgement, it is stated that the aim of...","{'text': ['entire human groups'], 'answer_star..."
1314,5733bc38d058e614000b6187,Antibiotics,The emergence of resistance of bacteria to ant...,What is a modern common occurence with antibio...,"{'text': ['resistance of bacteria'], 'answer_s..."
...,...,...,...,...,...
86528,5732977f0342181400a20283,Police,A police force is a constituted body of person...,What does the state want a police force to do?,"{'text': ['enforce the law, protect property, ..."
86696,5733f55e4776f419006615ab,"Punjab,_Pakistan","Punjab (Urdu, Punjabi: پنجاب, panj-āb, ""five w...",What does Punjab mean?,"{'text': ['five waters'], 'answer_start': [40]}"
86822,57341ab74776f4190066187b,Infection,"Among the vast varieties of microorganisms, r...","Of the huge amount of microorganisms, how many...","{'text': ['relatively few'], 'answer_start': [..."
86966,573443cb879d6814001ca423,Hunting,Hunting is the practice of killing or trapping...,What is the practice of killing or trapping an...,"{'text': ['Hunting'], 'answer_start': [0]}"
87323,57359bbcdc94161900571ee9,Kathmandu,Kathmandu(/ˌkɑːtmɑːnˈduː/; Nepali pronunciatio...,What country is Kathmandu the capital of?,"{'text': ['Nepal'], 'answer_start': [105]}"