In [1]:
import pandas as pd

In [3]:
csv_file = r'C:\Users\playe\Documents\Trabajos\TFG-RAG-VDB\src\Resulsts\resultados_rag_500.csv'
df = pd.read_csv(csv_file)
df

,Pregunta,Respuesta_Generada,Respuesta_Esperada,Nota_Correctness,Justificacion
0,How many people in Kazakhstan speak Russian na...,Approximately 4.2 million native speakers.,The correct answer to the question 'How many p...,0.818757,The actual output correctly identifies the num...
1,In which year did Popper give a secret intervi...,1969,The correct answer to the question 'In which y...,0.635241,"The actual output provides the correct year, 1..."
2,Rhythmic gymnastics places greater emphaises o...,Acrobatics.,The correct answer to the question 'Rhythmic g...,0.400541,The actual output 'Acrobatics' partially addre...
3,Which Iranian scientist co-invented the first ...,Ali Javan.,The correct answer to the question 'Which Iran...,0.739926,The actual output correctly identifies Ali Jav...
4,Miami is located in which Florida county?,Miami is located in Miami-Dade County.,The correct answer to the question 'Miami is l...,0.767918,The actual output correctly identifies that Mi...
...,...,...,...,...,...
485,What is another name for Universal Studios Inc.?,Universal Pictures.,The correct answer to the question 'What is an...,0.865206,The actual output correctly identifies Univers...
486,When was the last time the Chicago Cubs appear...,1945,The correct answer to the question 'When was t...,0.870948,The actual output correctly identifies the yea...
487,Which Apple engineer led original iPod design ...,Jon Rubinstein led the original iPod design gr...,The correct answer to the question 'Which Appl...,0.751421,The actual output correctly identifies Jon Rub...
488,What is the plot from which film speed is deri...,The plot is called the D–log H curve or Hurter...,The correct answer to the question 'What is th...,0.845182,The actual output correctly identifies the plo...
489,How much difficulty do contemporary Czechs hav...,Contemporary Czechs have little difficulty und...,The correct answer to the question 'How much d...,0.831037,The actual output accurately conveys the core ...

In [9]:
df_suspensos = df[df['Nota_Correctness'] < 0.5]
df_suspensos[['Nota_Correctness', 'Pregunta']]

     Nota_Correctness                                           Pregunta
2            0.400541  Rhythmic gymnastics places greater emphaises o...
5            0.205208        Of what area was Valencia the largest city?
10           0.100000  What year was the turning point for Germany in...
11           0.207346  A medical staff training college named in his ...
12           0.430431                 Could a club appeal a requirement?
..                ...                                                ...
468          0.398920  How many buses does the region have for public...
470          0.277287  Why does race undermine social cohesion in Ame...
476          0.185010           With whom was he said to have conspired?
478          0.419252  How have the enlisted forces of the US Air For...
479          0.164276             What is formed by Chinese principles?

[113 rows x 2 columns]